export interface Coin {
    id: number,
    coingecko_id: string,
    name: string,
    symbol: string,
    description: string|null,
    image_url: string,
    current_price: number,
    market_cap: number,
    market_cap_rank: number,
    fully_diluted_valuation: number|null,
    total_volume: number|null,
    high_24h: number|null,
    low_24h: number|null,
    price_change_24h: number|null,
    price_change_percentage_24h: number|null,
    market_cap_change_24h: number|null,
    market_cap_change_percentage_24h: number|null,
}